import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NewYorkClock from "@/components/NewYorkClock";
import ClockGrid from "@/components/ClockGrid";
import ClockWrapper from "@/components/ClockWrapper";
import NewDelhiClock from "@/components/NewDelhiClock";
import ParisClock from "@/components/ParisClock";
import LondonClock from "@/components/LondonClock";
import TokyoClock from "@/components/TokyoClock";
import BeijingClock from "@/components/BeijingClock";

export async function getStaticProps() {
  return {
    props: {},
  };
}

export default function Home() {
  return (
    <>
      <Head>
        <title>React Wall Clocks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ClockGrid>
          <ClockWrapper>
            <NewYorkClock size={300} />
            <h3>New York</h3>
          </ClockWrapper>
          <ClockWrapper>
            <NewDelhiClock size={300} />
            <h3>New Delhi</h3>
          </ClockWrapper>
          <ClockWrapper>
            <ParisClock size={300} />
            <h3>Paris</h3>
          </ClockWrapper>
          <ClockWrapper>
            <LondonClock size={300} />
            <h3>London</h3>
          </ClockWrapper>
          <ClockWrapper>
            <TokyoClock size={300} />
            <h3>Tokyo</h3>
          </ClockWrapper>
          <ClockWrapper>
            <BeijingClock size={300} />
            <h3>Beijing</h3>
          </ClockWrapper>
        </ClockGrid>
      </main>
    </>
  );
}
